version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
  redis:
    image: redis:latest
    restart: always
    command:
      - 'redis-server'
      - '--loglevel debug'
      - '--databases 2'
    hostname: redis
    ports:
      - 5672:5672
  web:
    build: .
    environment:
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      SECRET_KEY: $SECRET_KEY
      PYTHONIOENCODING: utf-8
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/quiz
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    environment:
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      SECRET_KEY: $SECRET_KEY
      PYTHONIOENCODING: utf-8
    command: celery -A questions worker --loglevel info
    volumes:
      - .:/quiz
    depends_on:
      - db
      - redis
    links:
      - redis
