# Generated by Django 2.1.5 on 2019-02-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='question',
        ),
        migrations.AddField(
            model_name='testrun',
            name='questions',
            field=models.ManyToManyField(related_name='testrun', to='questions.Question'),
        ),
    ]
