# Generated by Django 2.1.5 on 2019-02-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190205_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='questions',
        ),
        migrations.AddField(
            model_name='testrun',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='testruns', to='questions.Question'),
            preserve_default=False,
        ),
    ]
