# Generated by Django 2.1.5 on 2019-02-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190207_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'ordering': ['id']},
        ),
    ]
