# Generated by Django 2.1.5 on 2019-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_test_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='blocked',
            field=models.BooleanField(null=True),
        ),
    ]
