# Generated by Django 2.1.5 on 2019-02-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_test_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='blocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testrun', to=settings.AUTH_USER_MODEL),
        ),
    ]
