# Generated by Django 2.1.5 on 2019-02-27 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20190221_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='creator',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='test', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrunanswer',
            name='testrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testrun_answer', to='questions.Testrun'),
        ),
    ]
