# Generated by Django 2.1.5 on 2019-03-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20190227_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='name',
            new_name='user',
        ),
    ]
